### ISSUE TITLE
Error in graphics.go: undefined: chart.StyleShow

### ISSUE THREAD

**Issue by ddyok** [corywalker/expreduce#193]
I get this when go getting from scratch:

```
~$ go get github.com/corywalker/expreduce

# github.com/corywalker/expreduce/expreduce/graphics
go/src/github.com/corywalker/expreduce/expreduce/graphics/graphics.go:162:11: undefined: chart.StyleShow
go/src/github.com/corywalker/expreduce/expreduce/graphics/graphics.go:165:11: undefined: chart.StyleShow
go/src/github.com/corywalker/expreduce/expreduce/graphics/graphics.go:179:3: unknown field 'Show' in struct literal of type chart.Style
```

**Comment by andlabs** [comment]
StyleShow was deleted in https://github.com/wcharczuk/go-chart/commit/45fad0cfb8e64e6314abeeaf381102aad6d9279c, "switching to geneators"; the examples were not changed. I'm going to try to roll back to 2d5aeaf824f4b3be7c0b27ea89327eeff6b6e93a in the meantime; will report back.

**Comment by andlabs** [comment]
Ah no, I was wrong; it was actually deleted in an earlier commit than that. 9852fce5a172598e72d16f4306f0f17a53d94eb4 works.
