### ISSUE TITLE
Question about rules

### ISSUE THREAD

**Issue by cznic** [corywalker/expreduce#43]
I found some information about pattern matching and rules for rewriting for Mathics/SymPy (IIRC) which seem to apply to expreduce. So far I was not able to figure out how to have something like a local "subrule".

Having some rule like x -> {y, z, w} where y, z, and w share a large amount of whatever, can that whatever be somehow/easily/safely factored out? Ex.:

```
Solve[x_, a_*x_^2 + b_*x_ + c_ == d_] := {{x -> (-b - Sqrt[b^2 - 4 a c + 4 a d])/(2 a)}, {x -> (-b + Sqrt[b^2 - 4 a c + 4 a d])/(2 a)}}
```

Can the `Sqrt[b^2 - 4 a c + 4 a d]` be somewhere defined only once?

Probably a silly question, but I haven't yet enough time to properly study the matter and I'm looking for a hint/crash course on the topic. Thank you.

**Comment by corywalker** [comment]
This is possible. You can try using something like:

`Solve[x_, a_*x_^2 + b_*x_ + c_ == d_] := {{x -> (-b - common)/(2 a)}, {x -> (-b + common)/(2 a)}} /. common -> Sqrt[b^2 - 4 a c + 4 a d]`

You can apply rules to rules :P

**Comment by cznic** [comment]
So easy ;-)

Thanks a lot!
