### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by carlca** [corywalker/expreduce#71]
Hi Cory, I installed `expreduce` and ran `go run calc.go` in the `example` folder. I received the message: 
```
calc.go:7:2: cannot find package "gopkg.in/readline.v1" in any of:
	/usr/local/go/src/gopkg.in/readline.v1 (from $GOROOT)
	/Users/carlca/Code/go/src/gopkg.in/readline.v1 (from $GOPATH)
```

I then found this package https://gopkg.in/readline.v1

I ran `go get gopkg.in/readline.v1` and then ran `go run calc.go` again. This time I got the error:

```
# command-line-arguments
./calc.go:27: undefined: readline in readline.NewEx
```

Any ideas?

**Comment by carlca** [comment]
On the plus side, I'm pleased to report that the test apps are all working!

**Comment by corywalker** [comment]
This is my fault. I'm still figuring out the go packaging practices. I think I have everything fixed in the master branch now. You should now be able to just run this:

`go get github.com/corywalker/expreduce`

and the `expreduce` command will bring up the shell from anywhere since the binary should install into your GOPATH. I've updated the README to reflect this, and I'll update the documentation site soon. Thanks for bringing this to my attention. Please let me know if you have any further issues.

**Comment by carlca** [comment]
macOS 10.12.6
Golang 1.8.3

Hi, Cory, I've just reinstalled, and the `expreduce` command doesn't do anything. When you say the binary installs into `GOPATH`, I didn't think that this affected binaries in the same way as installing into `PATH` does. I'm a newcomer to macs and *nix type OS's in general so I may be talking rubbish here!

**Comment by cznic** [comment]
@carlca 
> Hi, Cory, I've just reinstalled, and the expreduce command doesn't do anything.

Doesn't do anything is a bit blurry. Please specify exactly how you started the command and exactly what happened afterwards.

**Comment by cznic** [comment]
FTR

```bash
jnml@r550:~/src/github.com/corywalker/expreduce$ git branch 
* master
jnml@r550:~/src/github.com/corywalker/expreduce$ git pull
Already up-to-date.
jnml@r550:~/src/github.com/corywalker/expreduce$ git log -1
commit 33bcb65b8f6d7071dc5be5c10f6dcd85756c3184
Merge: 316840f b531d78
Author: Cory Walker <cwalker32@gmail.com>
Date:   Tue Jul 25 21:34:47 2017 -0700

    Merge pull request #73 from corywalker/travis-change
    
    Also test Go 1.8.
jnml@r550:~/src/github.com/corywalker/expreduce$ go install -v
github.com/corywalker/mathbigext
github.com/op/go-logging
github.com/stretchr/testify/vendor/github.com/davecgh/go-spew/spew
github.com/stretchr/testify/vendor/github.com/pmezard/go-difflib/difflib
gopkg.in/readline.v1
github.com/stretchr/testify/assert
github.com/corywalker/expreduce/expreduce
github.com/corywalker/expreduce
jnml@r550:~/src/github.com/corywalker/expreduce$ expreduce
Welcome to Expreduce!

In[1]:= ^C
jnml@r550:~/src/github.com/corywalker/expreduce$ 
```

HTH

**Comment by carlca** [comment]
@cznic 

> Doesn't do anything is a bit blurry. Please specify exactly how you started the command and exactly what happened afterwards.

From the macOS shell prompt (ZSH) I typed `expreduce` and pressed carriage return.
I received the error message: `zsh: command not found: expreduce`

Hard to provide more details than that, sorry!

**Comment by cznic** [comment]
> Hard to provide more details than that, sorry!

That's enough information to now know what 'does not do anything' actually stands for ;-)

Please try

```bash
$ cd $GOPATH/src/github.com/corywalker/expreduce
$ go install -v -a -x
...
$
```

Instead of the three dots you should see a lot of output. Within it look for where the expreduce binary was installed. I guess it'll be in $GOPATH/bin and I guess that path is not in your $PATH. Add the target path to your $PATH and then you should be able to execute the expreduce command.

Depending on where and how do you set your GOPATH, you may need to first start a new terminal window (.bashrc) or new user session (.profile).

**Comment by carlca** [comment]
What on earth did that go install -v -a -x command actually do? It must have produced a couple of hundred )(if not more) lines of output. I do hope it hasn’t made any irreversible changes to my system...

**Comment by cznic** [comment]
> What on earth did that go install -v -a -x command actually do? It must have produced a couple of hundred )(if not more) lines of output. I do hope it hasn’t made any irreversible changes to my system...

Nothing harmful should have happened. Can you find the line where the binary is installed? It should be somewhere near the end of that long list.

**Comment by carlca** [comment]
It’s ok, I did get rather freaked out by the explosion of activity! On closer examination, I can see that, indeed, nothing harmful happened. I found the location of the binary, and I’m just having a tidy up of my .zshrc file and will set the $PATH to include the $GOBIN stuff.

**Comment by corywalker** [comment]
@carlca, I'm not sure if you're still wrestling with go/compilation. If it helps, I've added binary releases for v0.2 for Linux/OSX/Windows. I found a neat utility that builds these automatically, so this should be happening much more often.

**Comment by carlca** [comment]
Cory, sounds good to me! Thanks a lot.

Cheers,
Carl
